version: "3.7"

volumes:
  bundle: # bundles
  node_modules:

services:
  app:
    image: alpinelab/ruby-dev:3.1.2
    command: yarn run dev
    ports:
      - "8000:8000"
      - "35729:35729"
    volumes:
      - .:/app
      - bundle:/bundle
      - node_modules:/app/node_modules
